### PR TITLE
add potential Dockerfile + test.sh

### PR DESCRIPTION
**Pull request by psathyrella**
I'm not sure if we want to add a Dockerfile, but i was having a fair bit of difficulty installing gctree using the pip/conda instructions so I put this together (copying some graphics/qt-fu from jared's [gcreplay dockerfile](https://github.com/matsengrp/gcreplay/blob/main/nextflow/docker/Dockerfile)) and it seems to work.

### CODE REVIEW

**Comment by willdumm** [comment]
This will be very nice to have, but I'm curious what issues you were having with the Conda install?

**Comment by psathyrella** [comment]
I don't have the error messages on my laptop at home, although I could dig around at work, but basically I tried a ton of combinations of versions to get the pip gctree install and conda phylip install to both work and did not succeed. I think the sticking point was always pyqt5.

**Comment by willdumm** [comment]
Yes, this has caused me lots of problems too. If you have a chance I'd love to hear if the new [conda installation instructions](https://matsengrp.github.io/gctree/install.html) work for you, if you haven't tried them already. I don't know if this is your issue, but there seems to be a problem with the package versions that `ete` specifies as dependencies (it's incompatible with Python 3.10, for example, but allows itself to be installed in a Python 3.10 environment). Attempting to render trees causes type errors from PyQt.

I intend to fix this by enforcing Python <=3.9 in the Conda recipe, but for now you just have to specify 3.9 when you create the environment.

**Comment by psathyrella** [comment]
welp, that would have saved me most of monday ;-)

yeah that seems to work.

**Comment by willdumm** [comment]
Well, considering that I submitted gctree to Conda-forge weeks ago, but just got around to changing the installation docs on Monday (probably while you were struggling with this) I feel bad. But thanks for the nice Dockerfile!

**Comment by willdumm** [comment]
@WSDeWitt assuming you want to merge this, I'll add a section in the installation docs acknowledging its existence, as well as the existence of the new test script in `tests`.

**Comment by WSDeWitt** [comment]
Sure, I'm all for it—thanks! Should we add the test script to `make test` for CI? It looks like the relevant ETE issue is etetoolkit/ete#616, so I suggest we create an issue and link to that, so we can remember to remove the python version constraint when possible.

**Pull request merged**
